### ISSUE TITLE
chore: .clang-format configuration item potential problem

### ISSUE THREAD

**Issue by xuthus5** [openGemini/opengemini-client-cpp#15]
> this is what the IDE fedback to me, I'm not sure if this is the real problem.

I found that the configuration content of this line does not match the schema:

```
"SortIncludes": {
    "title": "Controls if and how clang-format will sort `#includes`.",
    "enum": [
            "Never",
            "CaseSensitive",
            "CaseInsensitive"
          ],
    "type": "string"
}
```

https://github.com/openGemini/opengemini-client-cpp/blob/aaee2aa47332e0d4d955fd3bb8b2994084b70a30/.clang-format#L94

The AlignEscapedNewlinesLeft configuration item does not exist:

https://github.com/openGemini/opengemini-client-cpp/blob/aaee2aa47332e0d4d955fd3bb8b2994084b70a30/.clang-format#L21

**Comment by hiiiik** [comment]
Thanks for your feedback. It seems the IDE is doing some extra checks on the configuration to make sure using the latest options, so the clang-format itself should work fine.

Maybe we can remove the `AlignEscapedNewlinesLeft` option because it is deprecated since clang-format 5.0 and just retained for backwards compatibility.

And I prefer to leave the 'SortIncludes' as it is, its value type is boolean value until clang-format 13.0.

**Comment by xuthus5** [comment]
Thanks for the answer.
